name: Deploy to GCS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Initialize Terraform with backend config
        run: |
          cd terraform
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="prefix=terraform/state"
      
      - name: Apply Terraform
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}"
      
      - name: Get bucket name
        id: get_bucket
        run: |
          cd terraform
          # Capture only the valid bucket URL (first match) and remove any extra output.
          BUCKET_URL=$(terraform output -no-color -raw bucket_name 2>/dev/null | grep -o 'gs://[a-zA-Z0-9-]*' | head -n 1)
          # Remove the "gs://" prefix.
          BUCKET_NAME=$(echo "$BUCKET_URL" | sed 's|gs://||')
          # Use printf to ensure proper formatting when appending.
          printf "BUCKET_NAME=%s\n" "$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "Using bucket: $BUCKET_NAME"
      
      - name: Upload files to GCS
        run: |
          gsutil -m rsync -r build gs://${{ steps.get_bucket.outputs.BUCKET_NAME }}
      
      - name: Output deployment information
        run: |
          cd terraform
          echo "Load Balancer IP: $(terraform output -raw load_balancer_ip)"
          echo "Bucket URL: $(terraform output -raw bucket_url)"